#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12
bspc config normal_border_color "#0074e4"
bspc config focused_border_color "#A54242"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
nitrogen --restore &
picom &
dunst &
